In [53]:
import pandas as pd
import os

In [54]:
repositorio = "https://github.com/pauvas20210715/PC3/raw/main/appendData/appendData/"

In [55]:
# creating file names into a list:
years=range(1,5)
fileNames=['level'+str(lvl)+'.xlsx' for lvl in lvls]
# list of file names
fileNames

['level1.xlsx', 'level2.xlsx', 'level3.xlsx', 'level4.xlsx']

In [56]:
#generar el url para cada archivo
alltheLinks = [repositorio+fn for fn in fileNames]
alltheLinks

['https://github.com/pauvas20210715/PC3/raw/main/appendData/appendData/level1.xlsx',
 'https://github.com/pauvas20210715/PC3/raw/main/appendData/appendData/level2.xlsx',
 'https://github.com/pauvas20210715/PC3/raw/main/appendData/appendData/level3.xlsx',
 'https://github.com/pauvas20210715/PC3/raw/main/appendData/appendData/level4.xlsx']

In [57]:
#lista de DataFrames
allDFs= [pd.read_excel(link) for link in alltheLinks]
#asignando nombres a las columnas de cada uno
allColumnNames=[]
for df in allDFs:
    allColumnNames.append(set(df.columns))

In [58]:
[len(cols) for cols in allColumnNames]

[9, 12, 15, 10]

In [59]:
# details of common columns
commonColumns=set.intersection(*allColumnNames)
# expanding list of sets (*)
len(commonColumns),commonColumns

(8,
 {'Country',
  'Expected years of schooling',
  'GNI per capita rank minus HDI rank',
  'Gross national income (GNI) per capita',
  'HDI rank',
  'Human Development Index (HDI) ',
  'Life expectancy at birth',
  'Mean years of schooling'})

In [60]:
#columnas diferentes
set.union(*allColumnNames)-commonColumns
#se consideran despreciables

{'HDI rank.1',
 'Unnamed: 10',
 'Unnamed: 11',
 'Unnamed: 13',
 'Unnamed: 2',
 'Unnamed: 3',
 'Unnamed: 5',
 'Unnamed: 6',
 'Unnamed: 7',
 'Unnamed: 8',
 'Unnamed: 9',
 'le'}

In [61]:
#DF con las columnas comunes
dataframes=[df.loc[:,list(commonColumns)] for df in allDFs]

In [62]:
# Concatenar todos los DataFrames en uno solo
combined_df = pd.concat(dataframes, ignore_index=True)
combined_df

,Life expectancy at birth,Mean years of schooling,HDI rank,GNI per capita rank minus HDI rank,Gross national income (GNI) per capita,Human Development Index (HDI),Expected years of schooling,Country
0,83.9872,13.859660,1.0,5.0,66933.004540,0.962,16.500299,Switzerland
1,83.2339,13.003630,2.0,6.0,64660.106220,0.961,18.185200,Norway
2,82.6782,13.767170,3.0,11.0,55782.049810,0.959,19.163059,Iceland
3,85.4734,12.226210,4.0,6.0,62606.845400,0.952,17.278170,"Hong Kong, China (SAR)"
4,84.5265,12.726820,5.0,18.0,49238.433350,0.951,21.054590,Australia
...,...,...,...,...,...,...,...,...
190,61.6627,3.129267,187.0,4.0,731.786709,0.426,10.722722,Burundi
191,53.8947,4.334000,188.0,1.0,966.058611,0.404,8.040172,Central African Republic
192,61.5763,2.116717,189.0,-3.0,1239.866936,0.400,6.957112,Niger
193,52.5254,2.573774,190.0,-7.0,1364.169417,0.394,8.035914,Chad
194,54.9752,5.726140,191.0,-1.0,767.787000,0.385,5.542510,South Sudan

2. Merge entre ese archivo, y el archivo countryCODES.xlsx.

In [63]:
# Leer el archivo countryCODES.xlsx
countrys = pd.read_excel("https://github.com/pauvas20210715/PC3/raw/main/countryCODES.xlsx")
countrys

,Country,Officialstatename,InternetccTLD,iso2,iso3
0,AFGHANISTAN,The Islamic Republic of Afghanistan,.af,AF,AFG
1,ALBANIA,The Republic of Albania,.al,AL,ALB
2,ALGERIA,The People's Democratic Republic of Algeria,.dz,DZ,DZA
3,ANGOLA,The Republic of Angola,.ao,AO,AGO
4,ANTIGUA AND BARBUDA,Antigua and Barbuda,.ag,AG,ATG
...,...,...,...,...,...
166,UZBEKISTAN,The Republic of Uzbekistan,.uz,UZ,UZB
167,VIET NAM,The Socialist Republic of Viet Nam,.vn,VN,VNM
168,YEMEN,The Republic of Yemen,.ye,YE,YEM
169,ZAMBIA,The Republic of Zambia,.zm,ZM,ZMB
170,ZIMBABWE,The Republic of Zimbabwe,.zw,ZW,ZWE

In [64]:
#como los nombres están en mayúsculas, formateamos el DF inicial
combined_df['Country']=combined_df.Country.str.upper()
combined_df

,Life expectancy at birth,Mean years of schooling,HDI rank,GNI per capita rank minus HDI rank,Gross national income (GNI) per capita,Human Development Index (HDI),Expected years of schooling,Country
0,83.9872,13.859660,1.0,5.0,66933.004540,0.962,16.500299,SWITZERLAND
1,83.2339,13.003630,2.0,6.0,64660.106220,0.961,18.185200,NORWAY
2,82.6782,13.767170,3.0,11.0,55782.049810,0.959,19.163059,ICELAND
3,85.4734,12.226210,4.0,6.0,62606.845400,0.952,17.278170,"HONG KONG, CHINA (SAR)"
4,84.5265,12.726820,5.0,18.0,49238.433350,0.951,21.054590,AUSTRALIA
...,...,...,...,...,...,...,...,...
190,61.6627,3.129267,187.0,4.0,731.786709,0.426,10.722722,BURUNDI
191,53.8947,4.334000,188.0,1.0,966.058611,0.404,8.040172,CENTRAL AFRICAN REPUBLIC
192,61.5763,2.116717,189.0,-3.0,1239.866936,0.400,6.957112,NIGER
193,52.5254,2.573774,190.0,-7.0,1364.169417,0.394,8.035914,CHAD
194,54.9752,5.726140,191.0,-1.0,767.787000,0.385,5.542510,SOUTH SUDAN

In [65]:
# Realizar el merge. Asumimos que la clave común es 'Country'
merged_df = combined_df.merge(countrys,how='left', left_on='Country', right_on = 'Country')
merged_df

,Life expectancy at birth,Mean years of schooling,HDI rank,GNI per capita rank minus HDI rank,Gross national income (GNI) per capita,Human Development Index (HDI),Expected years of schooling,Country,Officialstatename,InternetccTLD,iso2,iso3
0,83.9872,13.859660,1.0,5.0,66933.004540,0.962,16.500299,SWITZERLAND,The Swiss Confederation,.ch,CH,CHE
1,83.2339,13.003630,2.0,6.0,64660.106220,0.961,18.185200,NORWAY,The Kingdom of Norway,.no,NO,NOR
2,82.6782,13.767170,3.0,11.0,55782.049810,0.959,19.163059,ICELAND,Iceland,.is,IS,ISL
3,85.4734,12.226210,4.0,6.0,62606.845400,0.952,17.278170,"HONG KONG, CHINA (SAR)",NaN,NaN,NaN,NaN
4,84.5265,12.726820,5.0,18.0,49238.433350,0.951,21.054590,AUSTRALIA,The Commonwealth of Australia,.au,AU,AUS
...,...,...,...,...,...,...,...,...,...,...,...,...
190,61.6627,3.129267,187.0,4.0,731.786709,0.426,10.722722,BURUNDI,The Republic of Burundi,.bi,BI,BDI
191,53.8947,4.334000,188.0,1.0,966.058611,0.404,8.040172,CENTRAL AFRICAN REPUBLIC,NaN,NaN,NaN,NaN
192,61.5763,2.116717,189.0,-3.0,1239.866936,0.400,6.957112,NIGER,NaN,NaN,NaN,NaN
193,52.5254,2.573774,190.0,-7.0,1364.169417,0.394,8.035914,CHAD,The Republic of Chad,.td,TD,TCD
194,54.9752,5.726140,191.0,-1.0,767.787000,0.385,5.542510,SOUTH SUDAN,The Republic of South Sudan,.ss,SS,SSD

In [71]:
#renombrando columnas
newNames = ['GNI', 'rank', 'years_school', 'life_exp', 'GNIminHDI','exp_school', 'HDI', 'country', 'of_name', 'TLD', 'iso2', 'iso3']
merged_df.columns = newNames
merged_df

,GNI,rank,years_school,life_exp,GNIminHDI,exp_school,HDI,country,of_name,TLD,iso2,iso3
0,83.9872,13.859660,1.0,5.0,66933.004540,0.962,16.500299,SWITZERLAND,The Swiss Confederation,.ch,CH,CHE
1,83.2339,13.003630,2.0,6.0,64660.106220,0.961,18.185200,NORWAY,The Kingdom of Norway,.no,NO,NOR
2,82.6782,13.767170,3.0,11.0,55782.049810,0.959,19.163059,ICELAND,Iceland,.is,IS,ISL
3,85.4734,12.226210,4.0,6.0,62606.845400,0.952,17.278170,"HONG KONG, CHINA (SAR)",NaN,NaN,NaN,NaN
4,84.5265,12.726820,5.0,18.0,49238.433350,0.951,21.054590,AUSTRALIA,The Commonwealth of Australia,.au,AU,AUS
...,...,...,...,...,...,...,...,...,...,...,...,...
190,61.6627,3.129267,187.0,4.0,731.786709,0.426,10.722722,BURUNDI,The Republic of Burundi,.bi,BI,BDI
191,53.8947,4.334000,188.0,1.0,966.058611,0.404,8.040172,CENTRAL AFRICAN REPUBLIC,NaN,NaN,NaN,NaN
192,61.5763,2.116717,189.0,-3.0,1239.866936,0.400,6.957112,NIGER,NaN,NaN,NaN,NaN
193,52.5254,2.573774,190.0,-7.0,1364.169417,0.394,8.035914,CHAD,The Republic of Chad,.td,TD,TCD
194,54.9752,5.726140,191.0,-1.0,767.787000,0.385,5.542510,SOUTH SUDAN,The Republic of South Sudan,.ss,SS,SSD

In [72]:
#hay columnas con missing values?
merged_df.isnull().sum()

GNI              2
rank             2
years_school     4
life_exp         2
GNIminHDI        2
exp_school       2
HDI              2
country          2
of_name         46
TLD             46
iso2            47
iso3            46
dtype: int64

In [73]:
#probablemente esto se debe a que no se corresponden los datos entre ambas DF
#eliminando los valores:
merged_df = merged_df.dropna()
merged_df

,GNI,rank,years_school,life_exp,GNIminHDI,exp_school,HDI,country,of_name,TLD,iso2,iso3
0,83.9872,13.859660,1.0,5.0,66933.004540,0.962,16.500299,SWITZERLAND,The Swiss Confederation,.ch,CH,CHE
1,83.2339,13.003630,2.0,6.0,64660.106220,0.961,18.185200,NORWAY,The Kingdom of Norway,.no,NO,NOR
2,82.6782,13.767170,3.0,11.0,55782.049810,0.959,19.163059,ICELAND,Iceland,.is,IS,ISL
4,84.5265,12.726820,5.0,18.0,49238.433350,0.951,21.054590,AUSTRALIA,The Commonwealth of Australia,.au,AU,AUS
5,81.3753,12.960490,6.0,6.0,60364.785950,0.948,18.714800,DENMARK,The Kingdom of Denmark,.dk,DK,DNK
...,...,...,...,...,...,...,...,...,...,...,...,...
188,59.3247,3.197642,185.0,2.0,1198.073924,0.446,10.219152,MOZAMBIQUE,The Republic of Mozambique,.mz,MZ,MOZ
189,58.9414,2.310000,186.0,-11.0,2132.629443,0.428,7.423038,MALI,The Republic of Mali,.ml,ML,MLI
190,61.6627,3.129267,187.0,4.0,731.786709,0.426,10.722722,BURUNDI,The Republic of Burundi,.bi,BI,BDI
193,52.5254,2.573774,190.0,-7.0,1364.169417,0.394,8.035914,CHAD,The Republic of Chad,.td,TD,TCD
194,54.9752,5.726140,191.0,-1.0,767.787000,0.385,5.542510,SOUTH SUDAN,The Republic of South Sudan,.ss,SS,SSD

In [74]:
#ordenando las columnas
merged_df.set_index(['country', 'of_name', 'rank', 'TLD', 'iso2', 'iso3'], inplace=True)
merged_df.head()

,,,,,,GNI,years_school,life_exp,GNIminHDI,exp_school,HDI
country,of_name,rank,TLD,iso2,iso3,,,,,,
SWITZERLAND,The Swiss Confederation,13.85966,.ch,CH,CHE,83.9872,1.0,5.0,66933.00454,0.962,16.500299
NORWAY,The Kingdom of Norway,13.00363,.no,NO,NOR,83.2339,2.0,6.0,64660.10622,0.961,18.185200
ICELAND,Iceland,13.76717,.is,IS,ISL,82.6782,3.0,11.0,55782.04981,0.959,19.163059
AUSTRALIA,The Commonwealth of Australia,12.72682,.au,AU,AUS,84.5265,5.0,18.0,49238.43335,0.951,21.054590
DENMARK,The Kingdom of Denmark,12.96049,.dk,DK,DNK,81.3753,6.0,6.0,60364.78595,0.948,18.714800

In [75]:
#orden alfabético
merged_df.sort_index(axis=1,inplace=True)

<ipython-input-75-42b5fab4ad70>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df.sort_index(axis=1,inplace=True)

In [76]:
#regresando los índices seleccionados
merged_df.reset_index(inplace=True)
#resultado
merged_df

,country,of_name,rank,TLD,iso2,iso3,GNI,GNIminHDI,HDI,exp_school,life_exp,years_school
0,SWITZERLAND,The Swiss Confederation,13.859660,.ch,CH,CHE,83.9872,66933.004540,16.500299,0.962,5.0,1.0
1,NORWAY,The Kingdom of Norway,13.003630,.no,NO,NOR,83.2339,64660.106220,18.185200,0.961,6.0,2.0
2,ICELAND,Iceland,13.767170,.is,IS,ISL,82.6782,55782.049810,19.163059,0.959,11.0,3.0
3,AUSTRALIA,The Commonwealth of Australia,12.726820,.au,AU,AUS,84.5265,49238.433350,21.054590,0.951,18.0,5.0
4,DENMARK,The Kingdom of Denmark,12.960490,.dk,DK,DNK,81.3753,60364.785950,18.714800,0.948,6.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...
143,MOZAMBIQUE,The Republic of Mozambique,3.197642,.mz,MZ,MOZ,59.3247,1198.073924,10.219152,0.446,2.0,185.0
144,MALI,The Republic of Mali,2.310000,.ml,ML,MLI,58.9414,2132.629443,7.423038,0.428,-11.0,186.0
145,BURUNDI,The Republic of Burundi,3.129267,.bi,BI,BDI,61.6627,731.786709,10.722722,0.426,4.0,187.0
146,CHAD,The Republic of Chad,2.573774,.td,TD,TCD,52.5254,1364.169417,8.035914,0.394,-7.0,190.0
147,SOUTH SUDAN,The Republic of South Sudan,5.726140,.ss,SS,SSD,54.9752,767.787000,5.542510,0.385,-1.0,191.0

In [77]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   country       148 non-null    object
 1   of_name       148 non-null    object
 2   rank          148 non-null    float64
 3   TLD           148 non-null    object
 4   iso2          148 non-null    object
 5   iso3          148 non-null    object
 6   GNI           148 non-null    float64
 7   GNIminHDI     148 non-null    float64
 8   HDI           148 non-null    float64
 9   exp_school    148 non-null    float64
 10  life_exp      148 non-null    float64
 11  years_school  148 non-null    float64
dtypes: float64(7), object(5)
memory usage: 14.0+ KB

3. Con los archivos fallecidosCOVID.csv, reporte mensual de fallecidos. Mostrar mes (y año) y cuantos fallecidos hubo.

In [78]:
# Leer el archivo fallecidosCOVID.csv
fallecidos = pd.read_csv("https://github.com/pauvas20210715/PC3/raw/main/fallecidosCOVID.csv")
fallecidos

       FECHA_CORTE;FECHA_FALLECIMIENTO;EDAD_DECLARADA;SEXO;CLASIFICACION_DEF;DEPARTAMENTO;PROVINCIA;DISTRITO;UBIGEO;UUID
0       20240317;20220219;63;MASCULINO;Criterio viroló...
1       20240317;20210529;74;MASCULINO;Criterio viroló...
2       20240317;20210623;72;FEMENINO;Criterio SINADEF...
3       20240317;20210824;85;MASCULINO;Criterio invest...
4       20240317;20210627;46;MASCULINO;Criterio viroló...
...                                                   ...
220913  20240317;20200809;77;MASCULINO;Criterio radiol...
220914  20240317;20201028;81;MASCULINO;Criterio clínic...
220915  20240317;20200515;68;FEMENINO;Criterio SINADEF...
220916  20240317;20210414;66;FEMENINO;Criterio clínico...
220917  20240317;20200819;61;MASCULINO;Criterio nexo e...

[220918 rows x 1 columns]

In [79]:
#se observa que las columnas están todas juntas
#hay que separarlas
fallecidos[['corte','fallecimiento', 'edad', 'sexo', 'criterio', 'dep', 'prov', 'dist', 'ubigeo', 'uuid']] =fallecidos['FECHA_CORTE;FECHA_FALLECIMIENTO;EDAD_DECLARADA;SEXO;CLASIFICACION_DEF;DEPARTAMENTO;PROVINCIA;DISTRITO;UBIGEO;UUID'].str.split(';', expand=True)
fallecidos

,FECHA_CORTE;FECHA_FALLECIMIENTO;EDAD_DECLARADA;SEXO;CLASIFICACION_DEF;DEPARTAMENTO;PROVINCIA;DISTRITO;UBIGEO;UUID,corte,fallecimiento,edad,sexo,criterio,dep,prov,dist,ubigeo,uuid
0,20240317;20220219;63;MASCULINO;Criterio viroló...,20240317,20220219,63,MASCULINO,Criterio virológico,TUMBES,TUMBES,TUMBES,240101,203506
1,20240317;20210529;74;MASCULINO;Criterio viroló...,20240317,20210529,74,MASCULINO,Criterio virológico,TUMBES,TUMBES,TUMBES,240101,203532
2,20240317;20210623;72;FEMENINO;Criterio SINADEF...,20240317,20210623,72,FEMENINO,Criterio SINADEF,TACNA,TACNA,ALTO DE LA ALIANZA,230102,203584
3,20240317;20210824;85;MASCULINO;Criterio invest...,20240317,20210824,85,MASCULINO,Criterio investigación Epidemiológica,TUMBES,TUMBES,TUMBES,240101,212541
4,20240317;20210627;46;MASCULINO;Criterio viroló...,20240317,20210627,46,MASCULINO,Criterio virológico,TACNA,TACNA,ALTO DE LA ALIANZA,230102,203665
...,...,...,...,...,...,...,...,...,...,...,...
220913,20240317;20200809;77;MASCULINO;Criterio radiol...,20240317,20200809,77,MASCULINO,Criterio radiológico,AREQUIPA,AREQUIPA,ALTO SELVA ALEGRE,040102,
220914,20240317;20201028;81;MASCULINO;Criterio clínic...,20240317,20201028,81,MASCULINO,Criterio clínico,LAMBAYEQUE,CHICLAYO,CHICLAYO,140101,
220915,20240317;20200515;68;FEMENINO;Criterio SINADEF...,20240317,20200515,68,FEMENINO,Criterio SINADEF,LIMA,LIMA,LA MOLINA,150114,
220916,20240317;20210414;66;FEMENINO;Criterio clínico...,20240317,20210414,66,FEMENINO,Criterio clínico,LIMA,LIMA,LOS OLIVOS,150117,
220917,20240317;20200819;61;MASCULINO;Criterio nexo e...,20240317,20200819,61,MASCULINO,Criterio nexo epidemiológico,PIURA,PIURA,TAMBO GRANDE,200114,

In [80]:
#eliminar la primera columna
fallecidos = fallecidos.drop(columns='FECHA_CORTE;FECHA_FALLECIMIENTO;EDAD_DECLARADA;SEXO;CLASIFICACION_DEF;DEPARTAMENTO;PROVINCIA;DISTRITO;UBIGEO;UUID')
fallecidos

,corte,fallecimiento,edad,sexo,criterio,dep,prov,dist,ubigeo,uuid
0,20240317,20220219,63,MASCULINO,Criterio virológico,TUMBES,TUMBES,TUMBES,240101,203506
1,20240317,20210529,74,MASCULINO,Criterio virológico,TUMBES,TUMBES,TUMBES,240101,203532
2,20240317,20210623,72,FEMENINO,Criterio SINADEF,TACNA,TACNA,ALTO DE LA ALIANZA,230102,203584
3,20240317,20210824,85,MASCULINO,Criterio investigación Epidemiológica,TUMBES,TUMBES,TUMBES,240101,212541
4,20240317,20210627,46,MASCULINO,Criterio virológico,TACNA,TACNA,ALTO DE LA ALIANZA,230102,203665
...,...,...,...,...,...,...,...,...,...,...
220913,20240317,20200809,77,MASCULINO,Criterio radiológico,AREQUIPA,AREQUIPA,ALTO SELVA ALEGRE,040102,
220914,20240317,20201028,81,MASCULINO,Criterio clínico,LAMBAYEQUE,CHICLAYO,CHICLAYO,140101,
220915,20240317,20200515,68,FEMENINO,Criterio SINADEF,LIMA,LIMA,LA MOLINA,150114,
220916,20240317,20210414,66,FEMENINO,Criterio clínico,LIMA,LIMA,LOS OLIVOS,150117,
220917,20240317,20200819,61,MASCULINO,Criterio nexo epidemiológico,PIURA,PIURA,TAMBO GRANDE,200114,

In [81]:
fallecidos

,corte,fallecimiento,edad,sexo,criterio,dep,prov,dist,ubigeo,uuid
0,20240317,20220219,63,MASCULINO,Criterio virológico,TUMBES,TUMBES,TUMBES,240101,203506
1,20240317,20210529,74,MASCULINO,Criterio virológico,TUMBES,TUMBES,TUMBES,240101,203532
2,20240317,20210623,72,FEMENINO,Criterio SINADEF,TACNA,TACNA,ALTO DE LA ALIANZA,230102,203584
3,20240317,20210824,85,MASCULINO,Criterio investigación Epidemiológica,TUMBES,TUMBES,TUMBES,240101,212541
4,20240317,20210627,46,MASCULINO,Criterio virológico,TACNA,TACNA,ALTO DE LA ALIANZA,230102,203665
...,...,...,...,...,...,...,...,...,...,...
220913,20240317,20200809,77,MASCULINO,Criterio radiológico,AREQUIPA,AREQUIPA,ALTO SELVA ALEGRE,040102,
220914,20240317,20201028,81,MASCULINO,Criterio clínico,LAMBAYEQUE,CHICLAYO,CHICLAYO,140101,
220915,20240317,20200515,68,FEMENINO,Criterio SINADEF,LIMA,LIMA,LA MOLINA,150114,
220916,20240317,20210414,66,FEMENINO,Criterio clínico,LIMA,LIMA,LOS OLIVOS,150117,
220917,20240317,20200819,61,MASCULINO,Criterio nexo epidemiológico,PIURA,PIURA,TAMBO GRANDE,200114,

In [82]:
#eliminar las columnas 'corte' y 'uuid' ya que son innecesarias
bye=['corte', 'uuid']
fallecidos = fallecidos.drop(columns=bye)
fallecidos

,fallecimiento,edad,sexo,criterio,dep,prov,dist,ubigeo
0,20220219,63,MASCULINO,Criterio virológico,TUMBES,TUMBES,TUMBES,240101
1,20210529,74,MASCULINO,Criterio virológico,TUMBES,TUMBES,TUMBES,240101
2,20210623,72,FEMENINO,Criterio SINADEF,TACNA,TACNA,ALTO DE LA ALIANZA,230102
3,20210824,85,MASCULINO,Criterio investigación Epidemiológica,TUMBES,TUMBES,TUMBES,240101
4,20210627,46,MASCULINO,Criterio virológico,TACNA,TACNA,ALTO DE LA ALIANZA,230102
...,...,...,...,...,...,...,...,...
220913,20200809,77,MASCULINO,Criterio radiológico,AREQUIPA,AREQUIPA,ALTO SELVA ALEGRE,040102
220914,20201028,81,MASCULINO,Criterio clínico,LAMBAYEQUE,CHICLAYO,CHICLAYO,140101
220915,20200515,68,FEMENINO,Criterio SINADEF,LIMA,LIMA,LA MOLINA,150114
220916,20210414,66,FEMENINO,Criterio clínico,LIMA,LIMA,LOS OLIVOS,150117
220917,20200819,61,MASCULINO,Criterio nexo epidemiológico,PIURA,PIURA,TAMBO GRANDE,200114

In [83]:
#comienza el formateo de las columnas
# Convertir la columna de fecha a datetime
pd.to_datetime(fallecidos['fallecimiento'])
fallecidos['fecha'] = pd.to_datetime(fallecidos['fallecimiento'])

In [84]:
# Extraer el año y el mes de la fecha
fallecidos['año'] = fallecidos['fecha'].dt.year
fallecidos['mes'] = fallecidos['fecha'].dt.month

In [85]:
# Agrupar por año y mes, y contar los fallecidos
reporte_mensual = fallecidos.groupby(['año', 'mes']).size().reset_index(name='fallecidos')

In [86]:
# Mostrar el reporte mensual
reporte_mensual

     año  mes  fallecidos
0   2020    3         181
1   2020    4        5134
2   2020    5       16363
3   2020    6       17462
4   2020    7       18501
5   2020    8       17668
6   2020    9        8437
7   2020   10        4471
8   2020   11        3229
9   2020   12        3885
10  2021    1       11175
11  2021    2       18645
12  2021    3       20691
13  2021    4       23110
14  2021    5       16692
15  2021    6        7722
16  2021    7        3481
17  2021    8        1850
18  2021    9        1140
19  2021   10        1066
20  2021   11        1107
21  2021   12        1283
22  2022    1        3562
23  2022    2        3503
24  2022    3        1299
25  2022    4         741
26  2022    5         625
27  2022    6         542
28  2022    7        1025
29  2022    8        1429
30  2022    9         892
31  2022   10         429
32  2022   11         272
33  2022   12         423
34  2023    1         371
35  2023    2         287
36  2023    3         295
37  2023    4         337
38  2023    5         323
39  2023    6         291
40  2023    7         258
41  2023    8         249
42  2023    9          60
43  2023   10          26
44  2023   11          33
45  2023   12          40
46  2024    1         249
47  2024    2          62
48  2024    3           2

4. Reporte de fallecidos por mes, pero el tipo de muerte debe estar en columnas separadas.

In [87]:
# Agrupar por año, mes y tipo de muerte, y contar los fallecidos
reporte_tipo_muerte = fallecidos.groupby(['año', 'mes', 'criterio']).size().unstack(fill_value=0).reset_index()

In [88]:
# Mostrar el reporte por tipo de muerte
reporte_tipo_muerte

criterio,año,mes,Criterio SINADEF,Criterio clínico,Criterio investigación Epidemiológica,Criterio nexo epidemiológico,Criterio radiológico,Criterio serológico,Criterio virológico,NotiCovid,sinadef
0,2020,3,35,52,25,2,7,2,58,0,0
1,2020,4,1793,541,498,68,182,778,1274,0,0
2,2020,5,6826,1152,1427,203,480,3233,3042,0,0
3,2020,6,5722,670,1706,251,391,5605,3117,0,0
4,2020,7,5012,609,1512,262,415,7501,3190,0,0
5,2020,8,4589,611,1456,208,534,7400,2870,0,0
6,2020,9,1984,475,755,105,233,3483,1402,0,0
7,2020,10,1091,463,469,50,172,1417,809,0,0
8,2020,11,704,462,307,37,186,867,666,0,0
9,2020,12,802,547,171,41,179,1047,1098,0,0
10,2021,1,2190,514,323,107,434,2448,5159,0,0
11,2021,2,4993,501,465,150,556,2539,9441,0,0
12,2021,3,6100,525,517,229,456,1703,11161,0,0
13,2021,4,7450,748,591,246,363,1488,12224,0,0
14,2021,5,5225,628,349,155,283,1175,8877,0,0
15,2021,6,2723,116,123,51,138,746,3825,0,0
16,2021,7,1025,113,67,35,68,521,1652,0,0
17,2021,8,578,75,22,15,36,287,837,0,0
18,2021,9,554,12,0,0,0,190,384,0,0
19,2021,10,469,12,0,0,0,148,437,0,0
20,2021,11,441,16,0,0,0,157,493,0,0
21,2021,12,585,8,0,0,0,133,557,0,0
22,2022,1,1894,22,0,0,0,41,1605,0,0
23,2022,2,1604,20,0,0,0,1,1878,0,0
24,2022,3,352,6,0,0,0,0,941,0,0
25,2022,4,131,9,0,0,0,0,601,0,0
26,2022,5,85,3,0,0,0,0,537,0,0
27,2022,6,81,3,0,0,0,0,458,0,0
28,2022,7,299,3,0,0,0,0,723,0,0
29,2022,8,405,6,0,0,0,0,1018,0,0
30,2022,9,154,12,0,0,0,0,726,0,0
31,2022,10,53,59,0,0,0,0,317,0,0
32,2022,11,23,0,0,0,0,0,249,0,0
33,2022,12,66,0,0,0,0,0,357,0,0
34,2023,1,34,1,0,0,0,0,336,0,0
35,2023,2,4,0,0,0,0,0,283,0,0
36,2023,3,6,0,0,0,0,0,289,0,0
37,2023,4,17,0,0,0,0,0,320,0,0
38,2023,5,6,0,0,0,0,0,317,0,0
39,2023,6,2,0,0,0,0,0,289,0,0
40,2023,7,3,0,0,0,0,0,255,0,0
41,2023,8,7,0,0,0,0,0,242,0,0
42,2023,9,7,0,0,0,0,0,53,0,0
43,2023,10,8,0,0,0,0,0,18,0,0
44,2023,11,13,0,0,0,0,0,20,0,0
45,2023,12,17,0,0,0,0,0,22,1,0
46,2024,1,35,0,0,0,0,0,83,115,16
47,2024,2,1,0,0,0,0,0,45,16,0
48,2024,3,0,0,0,0,0,0,2,0,0